#!/bin/bash

echo "🚀 GUIDE DE RÉSOLUTION - API Routes"
echo "=================================="
echo ""

echo "📊 DIAGNOSTIC ACTUEL :"
echo "✅ Google Calendar : INITIALISÉ"
echo "✅ Credentials OAuth2 : ACTIFS"  
echo "✅ Refresh Token : CONFIGURÉ"
echo "❌ Routes TRPC : 404 NOT FOUND"
echo "❌ Routes OAuth : 404 NOT FOUND"
echo ""

echo "🔧 ACTIONS REQUISES :"
echo ""
echo "1️⃣ REDÉPLOIEMENT VERCEL :"
echo "   - Allez sur https://vercel.com/dashboard"
echo "   - Sélectionnez le projet 'planning'"
echo "   - Cliquez sur 'Deployments'"
echo "   - Cliquez sur 'Redeploy' (bouton sur le dernier déploiement)"
echo "   - Attendez le rebuild complet"
echo ""

echo "2️⃣ VÉRIFICATION ENVIRONNEMENT :"
echo "   - Settings → Environment Variables"
echo "   - Vérifiez que GOOGLE_REFRESH_TOKEN est défini :"
echo "     1//036wt8eMutncaCgYIARAAGAMSNwF-L9IrYYVjwaU8Aom2Xu31hFufKfxX8TiMsCqa6Am8bdSzXUYk0hbKilAvYukmI47egIUWd5M"
echo ""

echo "3️⃣ TESTS POST-DÉPLOIEMENT :"
echo ""
echo "   Test 1 - Health Check :"
echo "   curl https://planning-7qkb7uw7v-ikips-projects.vercel.app/api/health"
echo "   → Doit retourner : {\"status\":\"ok\",\"googleCalendar\":\"initialized\"}"
echo ""

echo "   Test 2 - TRPC Endpoint :"
echo "   curl -X POST https://planning-7qkb7uw7v-ikips-projects.vercel.app/api/trpc/booking.getAvailableSlots \\"
echo "        -H 'Content-Type: application/json' \\"
echo "        -d '{\"input\": {\"date\": \"2025-12-08\"}}'"
echo "   → Doit retourner les créneaux disponibles"
echo ""

echo "   Test 3 - Page Patient :"
echo "   Ouvrir : https://planning-7qkb7uw7v-ikips-projects.vercel.app/book-appointment"
echo "   → Doit afficher les créneaux de rendez-vous (plus de 'Chargement...')"
echo ""

echo "4️⃣ SI PROBLÈME PERSISTE :"
echo "   - Vérifiez les logs Vercel dans l'onglet 'Functions'"
echo "   - Forcez un nouveau déploiement depuis Vercel"
echo "   - Contactez-moi avec les logs d'erreur"
echo ""

echo "🎯 RÉSULTAT ATTENDU :"
echo "   ✅ Créneaux visibles sur /book-appointment"
echo "   ✅ Sélection de date fonctionnelle"
echo "   ✅ Patients peuvent réserver des RDV"
echo ""

echo "📞 SUPPORT :"
echo "   Si les routes TRPC restent 404 après redéploiement,"
echo "   envoyez-moi les logs Vercel pour diagnostic avancé."